"""added idempotency_key in registration table

Revision ID: 05ce71f62588
Revises: 4c62a241d0d4
Create Date: 2026-03-25 10:53:41.432258

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05ce71f62588"
down_revision: Union[str, Sequence[str], None] = "4c62a241d0d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registrations", sa.Column("idempotency_key", sa.UUID(), nullable=True)
    )
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute(
        "UPDATE registrations SET idempotency_key = gen_random_uuid() WHERE idempotency_key IS NULL"
    )
    op.alter_column("registrations", "idempotency_key", nullable=False)
    op.create_unique_constraint(
        "uq_event_idempotency", "registrations", ["event_id", "idempotency_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_event_idempotency", "registrations", type_="unique")
    op.drop_column("registrations", "idempotency_key")
    # ### end Alembic commands ###
