"""update sync_table

Revision ID: 078334ee4ffb
Revises: a74217c692b1
Create Date: 2026-03-15 19:34:04.225619

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "078334ee4ffb"
down_revision: Union[str, Sequence[str], None] = "a74217c692b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
syncstatus = sa.Enum("PROCESSING", "FAILED", "SUCCESS", name="syncstatus")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    syncstatus.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "sync_logs",
        sa.Column("last_sync_time", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "sync_logs",
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column("sync_logs", sa.Column("sync_status", syncstatus, nullable=False))
    op.drop_column("sync_logs", "sync_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sync_logs",
        sa.Column(
            "sync_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("sync_logs", "sync_status")
    op.drop_column("sync_logs", "last_changed_at")
    op.drop_column("sync_logs", "last_sync_time")
    syncstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
